### ISSUE TITLE
Integrate Loop Mode

### ISSUE THREAD

**Issue by ariesco** [ariesco/MUnit#1]
Currently only assertTrue is integrated with the Loop. Hence, we need to integrate:
1. assertTrueMsg.
2. assertEqual.
3. assertReachable.
4. assertReachableBnd.
5. assertSort.

**Comment by jimbonauta** [comment]
y como lo integro??

2016-11-22 18:16 GMT+01:00 Adrián Riesco <notifications@github.com>:
